### ISSUE TITLE
Works Great!

### ISSUE THREAD

**Issue by CaptainPackers** [nikolas/mediawiki-export#1]
This is not an issue, but I can't see where or how Github allows for reviewing or thanking developers other than creating an issue!

This worked great! Thanks for developing and sharing it.

I was looking for a way to migrate content from MediaWiki to Dokuwiki. There aren't a lot of options available, but this script makes for a great start. I at least have my content in text files now.

**Comment by nikolas** [comment]
I'm glad you found it useful!
